styling done
Luckyaremu/react-bookstore pull request #6
Opened 2020-10-22 17:18 UTC by Luckyaremu

- styling done
- conflicts resolved
- linters error done

2020-10-23 19:12 UTC, Forison requested changes
## Status:: Changes Required❌
# 🙋‍♂️ @Luckyaremu 
#### You have done a good job on this one so far, here are some issue we have to address🤗.
* [ ] Styling is EXACTLY the same as the one provided in the designs 
([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone5/exactlySameAsDesign.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/45791599/))
- Let us add the add book row under the page just as in the picture of the requirement.
* [ ]  Let not forget to add an image of the design in the readme and make sure the live links, works. use `git push heroku milestone-5:master` to push to heroku from this branch.
### That is it kindly make these changes and submit a re-review👨‍🔧.
#### Happy coding👨‍💻
Addo Forison

2020-10-23 19:13 UTC, Forison commented on src/components/App.js
> +/* eslint-disable no-case-declarations */
- Do not make changes to eslint.
> note eslint configs should never be modified

2020-10-23 19:13 UTC, Forison commented on src/containers/BooksList.js
>  /* eslint-disable no-case-declarations */
- Do not make changes to eslint.
> note eslint configs should never be modified

2020-10-23 21:04 UTC, bellom requested changes
## Hi @Luckyaremu :clap: 

**Great work making `almost` all the necessary corrections from the previous review.**

# Status: Changes Required! ♻️ 

1. The live link is broken;
![image](https://user-images.githubusercontent.com/31897434/97051621-5ff33d00-1577-11eb-8c2d-71c328941963.png)

2. I saw just one commit; which you removed the eslint inline comment as you were told by @Forison, kindly attend to the changes mentioned by @Forison .

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-10-25 18:04 UTC, jofer86 approved these changes
## `const PROJECT_STATUS = "APPROVED"` 🚀 🚀 🚀 
## :wave: :wave: Hello! I'm Jorge, and  I will be conducting this code review. Let me get a closer look 🔎 🔍 🔎 🔍 🕵🏼 
- It seems like all of the required changes were met, great job!!! You might move along now. Milestone complete!!
--------------------------------------------------------------------
**Rock on**  🤘🏼 
**_Jorge Fernando Rincón Figueroa._** 
Technical Support Engineer.

2020-10-25 18:50 UTC, merged